[build]
  publish = "."

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

# Cache de assets estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"
